# A custom Iosevka build that's based on the old Zed Mono with some additional tweaks
# This is is more loose and has more angly features

[buildPlans.IosevkaFhtZedMono]
family = "FhtZed Mono"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
# Keep bold the same as Iosevka's default
weights.Bold = { shape = 700, menu = 700, css = 700 }
# But make the Regular variant a bit thinner (it becomes like the Light one)
weights.Regular = { shape = 350, menu = 400, css = 400 }
# And make the font slightly wider by default
# widths.Normal = { shape = 500, menu = 5, css = "normal" }
# And make only upright/regular slopes
slopes.Upright = { angle = 0, shape = "upright", menu = "upright", css = "normal" }
slopes.Italic = { angle = 9.4, shape = "italic", menu = "italic", css = "italic" }

# Term variant for terminal emulators.
[buildPlans.IosevkaFhtZedTerm]
family = "FhtZed Term"
spacing = "term"
snapshotFamily = "FhtZed Mono"
snapshotFeature = {"NWID" = 1}
exportGlyphNames = true
# Keep bold the same as Iosevka's default
weights.Bold = { shape = 700, menu = 700, css = 700 }
# But make the Regular variant much thinner (it becomes like the Light one)
weights.Regular = { shape = 350, menu = 400, css = 400 }
# And make the font slightly wider by default
# widths.Normal = { shape = 500, menu = 5, css = "normal" }
# And make only upright/regular slopes
slopes.Upright = { angle = 0, shape = "upright", menu = "upright", css = "normal" }
slopes.Italic = { angle = 9.4, shape = "italic", menu = "italic", css = "italic" }
[buildPlans.IosevkaFhtZedTerm.variants]
inherits = "ss08"
# Inherit all changes from the main font, the only change is character width
inherit = "buildPlans.IosevkaFhtZedMono"


[buildPlans.IosevkaFhtZedMono.variants]
inherits = "ss08"
[buildPlans.IosevkaFhtZedMono.variants.design]
capital-n = "standard-serifless"
capital-w = "curly-serifless"
capital-x = "straight-serifless"
f = "serifless"
g = "double-storey"
l = "serifed"
x = "curly-serifless"
y = "straight-turn-serifless"
z = "straight-serifless"
capital-delta = "straight"
lower-delta = "rounded"
zero = "slashed"
four = "semi-open-serifless"
five = "upright-arched-serifless"
seven = "straight-serifed"
eight = "two-circles"
nine = "straight-bar"
asterisk = "penta-high"
underscore = "above-baseline"
caret = "medium"
paren = "normal"
brace = "curly"
number-sign = "slanted"
ampersand = "closed"
dollar = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "corner"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"

# ---
# Copy all changes from Mono font to Term variant

[buildPlans.IosevkaFhtZedTerm.variants.design]
capital-n = "standard-serifless"
capital-w = "curly-serifless"
capital-x = "straight-serifless"
f = "serifless"
g = "double-storey"
l = "serifed"
x = "curly-serifless"
y = "straight-turn-serifless"
z = "straight-serifless"
capital-delta = "straight"
lower-delta = "rounded"
zero = "slashed"
four = "semi-open-serifless"
five = "upright-arched-serifless"
seven = "straight-serifed"
eight = "two-circles"
nine = "straight-bar"
asterisk = "penta-high"
underscore = "above-baseline"
caret = "medium"
paren = "normal"
brace = "curly"
number-sign = "slanted"
ampersand = "closed"
dollar = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "corner"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
